-- CreateTable
CREATE TABLE "Visit" (
    "visitToken" TEXT NOT NULL,
    "visitorToken" TEXT NOT NULL,
    "longitude" REAL,
    "latitude" REAL,
    "continent" TEXT,
    "country" TEXT,
    "city" TEXT,
    "region" TEXT,
    "regionCode" TEXT,
    "postalCode" TEXT,
    "timezone" TEXT,
    "ip" TEXT,
    "referrer" TEXT,
    "referringDomain" TEXT,
    "userAgent" TEXT,
    "landingPage" TEXT,
    "browser" TEXT,
    "browserVersion" TEXT,
    "os" TEXT,
    "osVersion" TEXT,
    "deviceType" TEXT,
    "deviceModel" TEXT,
    "deviceVendor" TEXT,
    "utmSource" TEXT,
    "utmMedium" TEXT,
    "utmTerm" TEXT,
    "utmContent" TEXT,
    "utmCampaign" TEXT,
    "startedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Event" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "visitToken" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT,
    "host" TEXT,
    "hostname" TEXT,
    "href" TEXT,
    "orign" TEXT,
    "pathname" TEXT,
    "port" TEXT,
    "protcol" TEXT,
    "search" TEXT,
    "longitude" REAL,
    "latitude" REAL,
    "continent" TEXT,
    "country" TEXT,
    "city" TEXT,
    "region" TEXT,
    "regionCode" TEXT,
    "postalCode" TEXT,
    "timezone" TEXT,
    "ip" TEXT,
    "referrer" TEXT,
    "referringDomain" TEXT,
    "userAgent" TEXT,
    "landingPage" TEXT,
    "browser" TEXT,
    "browserVersion" TEXT,
    "os" TEXT,
    "osVersion" TEXT,
    "deviceType" TEXT,
    "deviceModel" TEXT,
    "deviceVendor" TEXT,
    "time" DATETIME NOT NULL,
    CONSTRAINT "Event_visitToken_fkey" FOREIGN KEY ("visitToken") REFERENCES "Visit" ("visitToken") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Visit_visitToken_key" ON "Visit"("visitToken");
